baseURL = 'https://wasmenezes.com/'
languageCode = 'en-us'
title = 'Waschington Menezes'

# Configurações de processamento de imagens para melhor qualidade
[imaging]
  resampleFilter = "Lanczos"
  quality = 95
  anchor = "Smart"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/WasMenezes"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/was.menezes/"

[params]
  goToTop = true

[Languages.en-gb.params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Was Menezes"
  name = "Sidharth R"
  description = "\"A vantagem de ter péssima memória é divertir-se muitas vezes com as mesmas coisas boas como se fosse a primeira vez.\""

# Allow to override webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"
